version: '3.3'

services:
  db:
    image: mysql:8.4.0
    restart: always
    container_name: nfa-database
    environment:
      MYSQL_DATABASE: 'nfa'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'user'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
